### ISSUE TITLE
Database naming changes

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1236]
As per https://gist.github.com/tobscure/b189580dd17b9def574f92692faa0e56

---

Edit by @luceos

- [x] update phpdoc
- [x] update existing properties in flarum/core where a renameColumn was executed #1344 
- [x] update properties in core extensions where a renameColumn was executed
- [x] modify the accessor in User for the avatar_url https://github.com/flarum/core/commit/c31c1ea062d7be4bc0214330e4a1e5d130815b73
- [x] migrations for core; #1344 
- [x] migrations for suspend ext
- [x] migrations for tags ext
- [ ] add indices see [comment by Toby](https://github.com/flarum/core/issues/127#issuecomment-370190948)
- [ ] solve preferences drop from users, table or column
  - [ ] user notifications table
  - [ ] all other preferences to columns on users

**Comment by franzliedke** [comment]
One more change: see https://github.com/flarum/core/commit/c31c1ea062d7be4bc0214330e4a1e5d130815b73.

**Comment by luceos** [comment]
@tobscure the api-keys will have a allowed_ips column, but you didn't mention it being nullable. I can safely assume it should be nullable right?

**Comment by tobscure** [comment]
yes :)

**Comment by luceos** [comment]
@flarum/core I suggest to @tobscure to change columns related to users to be postfixed with `_by`. A good example of this is:

Old: `hide_user_id`, new `hidden_user_id`, suggestion `hidden_by`.

Let me know what you think!

**Comment by luceos** [comment]
@tobscure can you explain to me what needs to be done with this:

![image](https://user-images.githubusercontent.com/504687/35140465-a13328c0-fcf7-11e7-9895-7a1329bf9828.png)

**Comment by franzliedke** [comment]
@luceos The `_by` postfix sounds sensible, is there any apparent convention in Toby's initial plan? If not, then go with it, I'd say.

As far as non-supported column types are concerned: if possible, we should avoid that, you are right. Can you list the columns (and their types) that use those strange types? (Or is that `value` column the only one?) Then we can decide on a case-by-case basis whether the benefits that those types give us may be worthy to keep.

**Comment by tobscure** [comment]
I believe I didn't initially propose a `_by` suffix because I was trying to consolidate conventions, and the user relationship is already covered by the foreign key convention:

* Foreign key -> `{verbed}_{entity}_id` (eg. hidden_user_id)
  * Verb can be omitted for primary relationship (eg. post author is just `user_id`)

`_by` on the other hand would be creating a special case for the `users` table, and makes the relationship with the `users` table non-explicit (it's not necessarily clear in the column name that the value of the column should be a user ID).

I'm not necessarily against this, just explaining the original reasoning.

---

The `posts_users` table is literally just those two columns. Other extensions (eg. likes) can add columns in the future.

Stick with blob for settings `value` then :)

**Comment by franzliedke** [comment]
Very good reasoning, Toby. That "no special case for user IDs" part convinced me. :wink:

**Comment by luceos** [comment]
Okay so:

- don't do the `_by`
- but do stick to existing laravel migrations builder methods

Got it.

**Comment by luceos** [comment]
Waiting for #1339 to be merged so the foreign key can work again.
