### ISSUE TITLE
v0.1.0 roadmap (old)

### ISSUE THREAD

**Issue by tobscure** [flarum/core#74]
***Note: This roadmap is very much out-of-date. We'll overhaul it soon.***

This is an overview of what's ahead for Flarum. Things to be aware of:
- The list of plans/todos may change at any point.
- There is no specific ship date for a stable release at this time.
- Have a feature request? Read the [FAQ](http://flarum.org/docs/faq).
## Big Picture

Our next step is to get to **version 0.1.0**. This will be the first version of Flarum that we recommend for use in production. However, in keeping with semantic versioning, we will still have room to iterate and improve the Extension API in subsequent 0.x versions.

In order to get there, we will release a series of betas. The major things that we are focusing on for these betas are:
- [ ] Make the installer solid
- [ ] Tidy up the API and documentation #246
- [ ] Increase test coverage #245
- [x] Make everything translatable #267 #266 #265
- [ ] Improve performance #127
- [x] Improve error handling #118
- [x] Anti-spam tools #271
- [ ] Improved text editor with formatting buttons and full-screen preview #309 
- [ ] Proper search engine optimization #189
- [ ] Add some missing administration options (logo upload, SMTP, SSL)
- [ ] Various improvements to core/bundled extensions
- [ ] Generalise the Likes extension to a "Rate" extension #306
- [ ] Keyboard shortcuts #155
- [ ] Rewrite the Pusher extension #321
- [ ] New extensions: Private Discussions, SSO, Reporting, Answers, Embed
### Core
- [ ] Make discussion titles searchable #257
- [ ] Implement more gambits #256
- [ ] Give users the ability to deactivate their account and destroy personal info #255
- [x] Add user online indicators #254
- [ ] Mechanism to detect if you've been logged out, prompt you to re-enter your password #253
- [ ] Design and implement reset password and error page UIs #252
- [ ] Slug transliteration #194
- [ ] Better composer minimize behaviour #191
- [ ] Affix discussion sidebar #190
- [ ] Search engine optimization #189
- [ ] Floating discussion title #157
- [ ] Keyboard shortcuts #155
- [ ] Discussion list infinite scrolling + loading placeholders #115
### Administration
- [x] Improve appearance page, allow logo upload #268
- [x] Add UI to configure SMTP settings #258
- [x] SSL support #167
- [ ] Allow API to be accessed with master key #205
### Installer
- [x] Complete prerequisite checking
- [x] Input validation
- [ ] Support other database drivers
- [x] Support database table name prefix #269
- [x] Support installation in subfolders #291
- [x] Make the consle/web installers do the same prerequisite checks
### Mentions
- [x] Add a contextual quote button when text is selected #320 
### Subscriptions
- [x] User setting to automatically follow discussions you start/reply to #310
### Suspend
- [ ] Give user a notification when they are suspended/unsuspended #322 
### Likes
- [ ] Generalise to a "Rate" extension #306 
### Pusher
- [ ] Rewrite the whole thing #321 
### Tags
- [ ] Apply a className to various elements based on the active tags #327 
- [ ] Allow tags to have default sort orders #328 
- [ ] Add ability to style tags with background images #329 
- [x] Add setting to allow discussion authors to edit tags #330 
### New extensions
- [ ] Private Discussions
- [x] SSO
- [x] Reporting
- [ ] Answers
- [x] Embed
- [x] Header Links
## Wishlist

This is a list of stuff we definitely want to do, but we’re not sure when. First things first!
- Drafts
- RTL support
- Admin dashboard #259
- Forum about/statistics page #134
- Extension Marketplace
- Easy upgrade process
- Migrators (esoTalk, FluxBB, others)
- Laravel integration #274

**Comment by Notanotherdotcom** [comment]
With regards to spam, I am fortunate enough to run a forum where Google indexes posts in a matter of minutes. This does have its own issues though in that it attracts spammers who realise they can get links on Google within minutes!

What I've had to do on this forum is make it so that for non-registered users (and therefore Google bots), posts from user accounts less than 24 hours old are hidden with the message "to prevent spam, this post will be invisible for 24 hours" or something like that. It could use some work as ideally you would hide a whole thread for 24 hours if the user was <24 hours old, but it has effectively cut spam right down (spammers must have realised they're fighting a losing battle there) and gives moderators a little time to deal with spam.

Strangely, when I suggested this idea to the popular forum developer concerned, they weren't interested - I'm not entirely sure they understood how effective it was but I would highly recommend it as a simple, effective tool in the anti-spam arsenal! Plus, to my knowledge, none of the other forum developers have tried this approach, so it's still unique at the moment ;)

**Comment by SolidOrphan** [comment]
I really don't like your 24h idea. You should be able to participate immediately to the community.

Flarum needs a captcha (ReCaptcha is my favorite) implemented.

**Comment by Notanotherdotcom** [comment]
I believe I've not made my suggstion clear. The post does appear to logged-in users instantly, just not to guests, so for the first 24 hours search engine spiders don't see that content.

It makes the manual spammers (the ones we used to have most problems with as they can easily pass any CAPTCHA) go away when they realise their links aren't hitting the search engines and the moderators have enough time to ban their accounts :)

**Comment by SolidOrphan** [comment]
but you also impact the good member of the board.

**Comment by Notanotherdotcom** [comment]
I don't understand? Members can see the new user's content. If the new user is logged in, they can see their own post. It's only bots and non-logged-in people who can't see the content for 24 hours - to everyone else the content displays as it always would.

**Comment by SolidOrphan** [comment]
But that's wrong in my opinion. I often browse for example reddit and if someone would post something interesting and if I'm logout (it happens often) I would be pissed.

**Comment by Notanotherdotcom** [comment]
I don't see how it is any different from options on other forums where you can set for admins/moderators to approve posts before they are visible? At least my way the discussion can happen immediately with replies.

I certainly don't think it should be the default, but it is far more effective than any spam prevention method out there so could be a good option/extension. Recaptcha etc just doesn't work against real people who are paid to post junk links on your forums so on very popular forums there is a need for something better.

**Comment by Notanotherdotcom** [comment]
In my implementation all I did was replace the post of the new user with a message saying something like "as you are new to this community, this message will be displayed in 24 hours for guest users as an anti-spam measure". I just don't see how that could annoy someone that much? It's pretty non-inflammatory and the issue goes away after 24 hours and every post after that doesn't go through this anti-spam process. I figure 24 hours for moderators to spot a spammer is enough time, but most forums don't have moderators covering them 24/7 hence this idea.

**Comment by tobscure** [comment]
@notanotherdotcom Interesting idea. You might be interested in [this discussion](https://meta.discourse.org/t/hiding-all-posts-from-new-users-for-24-hours/31385) about your idea over at Discourse meta.

Won't be in core, but would be perfect as an extension.

**Comment by DouglasdeMoura** [comment]
@Notanotherdotcom Why not use [Akismet](http://akismet.com/development/)?

**Comment by Luceos** [comment]
> Improve appearance page, allow logo upload

An extension now exists for this. Is this something we want to pull into the core of leave it an open task?
